name: aicare_binary_classification
channels:
 - conda-forge
dependencies:
 - python=3.12.4
 - python_abi=3.12
 - scikit-learn=1.5.0
 - pandas=2.2.2
 - matplotlib-base=3.8.4
 - catboost=1.2.5
 - optuna=3.6.1
 - ydata-profiling=4.9.0